backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Page d'accueil"
        name: "index"
        file: "index.html"
        fields:
          - { label: "Titre principal", name: "title", widget: "string" }
          - { label: "Texte d’intro", name: "intro", widget: "text" }
