backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "content"
    label: "Contenu"
    files:
      - label: "Page d'accueil"
        name: "index"
        file: "index.html"
        fields:
          - { label: "Titre", name: "title", widget: "string" }
          - { label: "Paragraphe", name: "body", widget: "text" }
